// Adapter for claude.ai.
//
// Claude's composer is also a contenteditable div (ProseMirror-based), reached
// via React, not a plain <textarea>. Class names here are typically
// hashed/generated by their build and not stable across deploys, so we
// deliberately avoid matching on class and prefer attribute-based selectors,
// layered from most to least specific.

window.TokenMeter = window.TokenMeter || {};

window.TokenMeter.adapter = (function () {
  const SELECTORS = [
    'div[contenteditable="true"][data-testid="chat-input"]',
    'div[contenteditable="true"].ProseMirror',
    'div[contenteditable="true"][class*="composer"]',
    'div[contenteditable="true"][placeholder]',
    'div[contenteditable="true"]',
  ];

  function findInput() {
    for (const sel of SELECTORS) {
      const el = document.querySelector(sel);
      if (el) return el;
    }
    return null;
  }

  function getText(el) {
    return el.innerText || "";
  }

  function setText(el, text) {
    el.focus();
    document.execCommand("selectAll", false, null);
    document.execCommand("insertText", false, text);
  }

  function findSendButton() {
    return (
      document.querySelector('button[aria-label*="Send"]') ||
      document.querySelector('button[aria-label*="send"]')
    );
  }

  /**
   * Scrape every message currently rendered in the conversation, in order.
   * Returns [{ role: "user"|"assistant", text: string }, ...].
   *
   * Verified directly against claude.ai's live DOM (see project history):
   *   - User messages: [data-testid="user-message"] — confirmed present and
   *     stable (count matched across repeated checks and scroll positions).
   *   - Assistant messages: .font-claude-response — confirmed present.
   *     NOTE: an earlier version of this file also tried a class named
   *     "font-user-message", which looked plausible from a quick DOM
   *     inspection but was actually the LITERAL string "!font-user-message"
   *     (Tailwind's "important" modifier prefix is part of the class name
   *     itself, not stripped) — a CSS class selector can't match that
   *     without escaping the "!", so `.font-user-message` silently matched
   *     nothing. That's why data-testid is used for user messages instead;
   *     it doesn't have this escaping problem and was reliable throughout.
   *   - No data-testid exists for assistant messages on claude.ai's current
   *     build — only the user side is tagged that way, which is why this
   *     uses an attribute selector for one role and a class selector for
   *     the other rather than one consistent selector for both.
   * Falls back to the structural heuristic only if NEITHER signal is found
   * at all, e.g. if Anthropic changes the DOM again in the future.
   */
  function scrapeHistory() {
    const userNodes = Array.from(document.querySelectorAll('[data-testid="user-message"]'));
    const assistantNodes = Array.from(document.querySelectorAll(".font-claude-response"));

    if (userNodes.length > 0 || assistantNodes.length > 0) {
      const tagged = [
        ...userNodes.map((el) => ({ el, role: "user" })),
        ...assistantNodes.map((el) => ({ el, role: "assistant" })),
      ];
      // Merge both node sets back into actual document order using
      // Node.compareDocumentPosition, since they were queried separately and
      // are not naturally interleaved — without this, messages would come
      // out in "all users, then all assistants" order instead of the real
      // conversation sequence, which would break pair-matching downstream.
      tagged.sort((a, b) => {
        const pos = a.el.compareDocumentPosition(b.el);
        if (pos & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
        if (pos & Node.DOCUMENT_POSITION_PRECEDING) return 1;
        return 0;
      });
      return tagged.map(({ el, role }) => ({ role, text: el.innerText || "" }));
    }

    return window.TokenMeter.boundedAscentHistory("main");
  }

  return {
    siteName: "Claude",
    findInput,
    getText,
    setText,
    findSendButton,
    scrapeHistory,
    // Anthropic does not publish Claude's tokenizer, so we never claim an
    // "exact" count here — always estimate, clearly labeled as approximate.
    tokenizerHint: "estimate-only",
  };
})();
